build:
  environment:
    php:
      version: 7.4

    node: v8.14.0

  tests:
    override:
      - command: 'composer test:coverage'
        coverage:
          file: 'output/code-coverage/clover.xml'
          format: 'clover'
