build:
  environment:
    php:
      version: 7.2

    node: v8.14.0

  tests:
    override:
      -
        command: 'composer unit:coverage'
        coverage:
          file: 'output/code-coverage/clover.xml'
          format: 'clover'
