name: Code Review

on: [push, pull_request]

jobs:
  general:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Caching npm
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js dependencies
        run: npm install

      - name: Linting general code
        run: npm run cs:lint

  php:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 2
      matrix:
        php: ['8.0', '7.4', '7.3', '7.2']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }} environment
        uses: nanasess/setup-php@v3.0.6
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Caching Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Linting PHP syntax
        run: composer cs:php

      - name: Linting PHP Coding Standard
        run: composer cs:lint

      - name: Running tests
        run: composer test
